<?xml version='1.0'?>
<package format='3'>
  <name>hpp_exec</name>
  <version>9.0.2</version>
  <description>ROS2 execution utilities for HPP-generated trajectories</description>
  <author>Paul Sardin</author>
  <maintainer email='guilhem.saurel@laas.fr'>Guilhem Saurel</maintainer>
  <license>BSD-2-Clause</license>

  <exec_depend>hpp_python</exec_depend>
  <!-- <exec_depend>pyhpp</exec_depend> -->
  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>trajectory_msgs</exec_depend>
  <exec_depend>control_msgs</exec_depend>
  <exec_depend>action_msgs</exec_depend>
  <exec_depend>builtin_interfaces</exec_depend>

  <buildtool_depend>cmake</buildtool_depend>
  <build_depend>jrl_cmakemodules</build_depend>

  <export>
    <build_type>cmake</build_type>
  </export>
</package>
