"""
Gripper coordination for HPP manipulation trajectories.

Detects grasp/release events from HPP constraint graph transitions and builds
execution segments with gripper actions as pre/post hooks.

Example:
    from hpp_exec import execute_segments
    from hpp_exec.gripper import segments_from_graph

    # Define your own gripper (any object with open() -> bool, close() -> bool)
    gripper = MyGripperController(...)

    segments = segments_from_graph(
        configs, times, graph,
        on_grasp=gripper.close,
        on_release=gripper.open,
    )

    execute_segments(segments, configs, times, joint_names=[...])
"""

from __future__ import annotations

import inspect
import logging
from collections.abc import Mapping
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Callable, Dict, List, Optional, Tuple

import numpy as np

if TYPE_CHECKING:
    from hpp_exec.ros2_sender import Segment

logger = logging.getLogger(__name__)

ActionSpec = (
    Callable[[], bool]
    | Callable[["GraspTransition"], bool]
    | Mapping[str, Callable[[], bool]]
)


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------


@dataclass
class GraspTransition:
    """A point in the trajectory where the manipulation graph transition changes."""

    config_index: int
    """Index in the configs list where this transition occurs."""

    time: float
    """Time at this config."""

    grasps_before: set[str]
    """Active grasp names before the transition."""

    grasps_after: set[str]
    """Active grasp names after the transition."""

    state_before: str = ""
    """Constraint graph state before crossing the transition."""

    state_after: str = ""
    """Constraint graph state after crossing the transition."""

    transition_name: Optional[str] = None
    """Name of the graph transition crossed between state_before and state_after."""

    acquired: set[str] = field(default_factory=set)
    """New grasps (close gripper)."""

    released: set[str] = field(default_factory=set)
    """Lost grasps (open gripper)."""

    def __post_init__(self):
        if not self.acquired and not self.released:
            self.acquired = self.grasps_after - self.grasps_before
            self.released = self.grasps_before - self.grasps_after


# ---------------------------------------------------------------------------
# Constraint graph state parsing
# ---------------------------------------------------------------------------


def _parse_grasps_from_state_name(state_name: str) -> set[str]:
    """Extract active grasp descriptions from an HPP constraint graph state name.

    HPP state names encode active grasps, e.g.:
        "free"                                    -> set()
        "r_gripper grasps box/handle"             -> {"r_gripper grasps box/handle"}
        "r_gripper grasps box/handle : l_gripper grasps cup/handle"
            -> {"r_gripper grasps box/handle", "l_gripper grasps cup/handle"}

    The separator between multiple grasps is " : " (space-colon-space).
    """
    if not state_name or state_name.strip().lower() == "free":
        return set()

    # HPP uses " : " to separate multiple active grasps in state names
    parts = [p.strip() for p in state_name.split(" : ")]
    return {p for p in parts if "grasps" in p.lower() or "grasp" in p.lower()}


def _grasp_label_from_transition_side(side: str) -> str:
    """Normalize one side of a transition name into a grasp label."""
    return side.strip().replace("  ", " ")


def _parse_grasp_event_from_transition_name(
    transition_name: Optional[str],
) -> tuple[set[str], set[str]]:
    """Extract acquired/released grasp labels from an HPP transition name.

    HPP manipulation transitions generated by the graph factory are typically
    named like:
        "fr3/gripper > box/handle | f_01"  (grasp)
        "fr3/gripper < box/handle | 0-0_12" (release)

    The state name may describe the resulting set of grasps, which is not
    enough to identify the event when states encode combinations such as
    "g1+g2". The transition name identifies the operation that was crossed.
    """
    if not transition_name:
        return set(), set()

    event_name = transition_name.split("|", 1)[0].strip()
    if " > " in event_name:
        gripper, handle = event_name.split(" > ", 1)
        return {
            f"{_grasp_label_from_transition_side(gripper)} grasps "
            f"{_grasp_label_from_transition_side(handle)}"
        }, set()

    if " < " in event_name:
        gripper, handle = event_name.split(" < ", 1)
        return set(), {
            f"{_grasp_label_from_transition_side(gripper)} grasps "
            f"{_grasp_label_from_transition_side(handle)}"
        }

    return set(), set()


def _build_transition_lookup(graph) -> Dict[Tuple[str, str], List[str]]:
    """Build a state-pair -> transition-name lookup from a pyhpp graph."""
    lookup: Dict[Tuple[str, str], List[str]] = {}

    if not hasattr(graph, "getTransitions") or not hasattr(
        graph, "getNodesConnectedByTransition"
    ):
        return lookup

    for transition in graph.getTransitions():
        try:
            state_from, state_to = graph.getNodesConnectedByTransition(transition)
            name = transition.name()
        except Exception as exc:
            logger.debug("Could not inspect graph transition: %s", exc)
            continue

        lookup.setdefault((state_from, state_to), []).append(name)

    return lookup


def _transition_name_between_states(
    lookup: Dict[Tuple[str, str], List[str]],
    state_before: str,
    state_after: str,
) -> Optional[str]:
    """Return the transition name for a state change, when it is unique."""
    names = lookup.get((state_before, state_after), [])
    if len(names) == 1:
        return names[0]
    if len(names) > 1:
        logger.warning(
            "Multiple graph transitions connect '%s' to '%s': %s. "
            "Falling back to state-name grasp detection.",
            state_before,
            state_after,
            names,
        )
    return None


def _callable_accepts_transition(action: Callable) -> bool:
    """Return whether action can be called with a GraspTransition argument."""
    try:
        signature = inspect.signature(action)
    except (TypeError, ValueError):
        return False

    positional = [
        p
        for p in signature.parameters.values()
        if p.kind
        in (
            inspect.Parameter.POSITIONAL_ONLY,
            inspect.Parameter.POSITIONAL_OR_KEYWORD,
        )
    ]
    has_varargs = any(
        p.kind == inspect.Parameter.VAR_POSITIONAL
        for p in signature.parameters.values()
    )
    required = [p for p in positional if p.default == inspect.Parameter.empty]
    return has_varargs or len(required) <= 1 <= len(positional)


def _action_keys_for_transition(
    transition: GraspTransition,
    event_grasps: set[str],
) -> list[str]:
    keys = []
    if transition.transition_name:
        keys.append(transition.transition_name)
    keys.extend(sorted(event_grasps))
    if transition.state_before or transition.state_after:
        keys.append(f"{transition.state_before} -> {transition.state_after}")
    return keys


def _resolve_action(
    action_spec: ActionSpec,
    transition: GraspTransition,
    event_grasps: set[str],
) -> Callable[[], bool]:
    """Resolve an action spec to the zero-arg callable stored on Segment."""
    if isinstance(action_spec, Mapping):
        for key in _action_keys_for_transition(transition, event_grasps):
            action = action_spec.get(key)
            if action is not None:
                if _callable_accepts_transition(action):
                    return lambda: action(transition)
                return action
        raise KeyError(
            "No action found for graph transition "
            f"{transition.transition_name!r}; tried keys "
            f"{_action_keys_for_transition(transition, event_grasps)!r}"
        )

    if _callable_accepts_transition(action_spec):
        return lambda: action_spec(transition)

    return action_spec


def extract_grasp_transitions(
    configs: List[np.ndarray],
    times: List[float],
    graph,
) -> List[GraspTransition]:
    """Detect grasp/release events by querying the HPP constraint graph.

    For each config, queries the constraint graph state. When the state changes
    between consecutive configs, the transition crossed between those states is
    used to identify the grasp/release event. This is more precise than using
    the destination state alone because states can encode combinations such as
    "g1+g2". If transition metadata is unavailable, the function falls back to
    comparing active-grasp sets parsed from state names.

    Args:
        configs: HPP configuration vectors along the path.
        times: Corresponding timestamps.
        graph: HPP manipulation constraint graph (pyhpp.manipulation.Graph).
            Must have getStateFromConfiguration(q). If it also provides
            getTransitions() and getNodesConnectedByTransition(edge), transition
            names are used to identify grasp/release events.

    Returns:
        Ordered list of GraspTransition at each state change.
    """
    if len(configs) < 2:
        return []

    transitions = []
    prev_state = graph.getStateFromConfiguration(configs[0])
    prev_grasps = _parse_grasps_from_state_name(prev_state)
    transition_lookup = _build_transition_lookup(graph)

    for i in range(1, len(configs)):
        state = graph.getStateFromConfiguration(configs[i])
        grasps = _parse_grasps_from_state_name(state)

        if state != prev_state or grasps != prev_grasps:
            transition_name = _transition_name_between_states(
                transition_lookup, prev_state, state
            )
            acquired, released = _parse_grasp_event_from_transition_name(
                transition_name
            )
            transitions.append(
                GraspTransition(
                    config_index=i,
                    time=times[i],
                    state_before=prev_state,
                    state_after=state,
                    transition_name=transition_name,
                    grasps_before=prev_grasps,
                    grasps_after=grasps,
                    acquired=acquired,
                    released=released,
                )
            )
            prev_state = state
            prev_grasps = grasps

    return transitions


# ---------------------------------------------------------------------------
# Segment builder from constraint graph
# ---------------------------------------------------------------------------


def segments_from_graph(
    configs: List[np.ndarray],
    times: List[float],
    graph,
    on_grasp: ActionSpec,
    on_release: ActionSpec,
) -> List["Segment"]:
    """Build execution segments from HPP constraint graph transitions.

    Detects graph transitions along the path and creates Segment objects with
    on_grasp/on_release assigned as pre-actions on the appropriate segments.

    Args:
        configs: Full HPP configuration vectors along the path.
        times: Corresponding timestamps.
        graph: HPP manipulation constraint graph (pyhpp.manipulation.Graph).
        on_grasp: Action to run when a grasp is acquired (e.g. gripper.close).
            This can be a zero-arg callable, a callable accepting the
            GraspTransition, or a dict keyed by transition name/grasp label.
        on_release: Action to run when a grasp is released (e.g. gripper.open).
            Supports the same forms as on_grasp.

    Returns:
        List of Segment objects ready for execute_segments().
    """
    from hpp_exec.ros2_sender import Segment

    transitions = extract_grasp_transitions(configs, times, graph)

    if not transitions:
        return [Segment(0, len(configs))]

    # Build segment boundaries: [0, t1, t2, ..., end]
    split_indices = [0] + [t.config_index for t in transitions] + [len(configs)]

    segments = []
    for i in range(len(split_indices) - 1):
        start = split_indices[i]
        end = split_indices[i + 1]

        pre_actions = []
        if i > 0:
            transition = transitions[i - 1]
            if transition.acquired:
                pre_actions.append(
                    _resolve_action(on_grasp, transition, transition.acquired)
                )
            if transition.released:
                pre_actions.append(
                    _resolve_action(on_release, transition, transition.released)
                )

        segments.append(Segment(start, end, pre_actions=pre_actions))

    return segments
