"""
Gripper coordination for HPP manipulation trajectories.

Detects grasp/release events from HPP constraint graph transitions and builds
execution segments with gripper actions as pre/post hooks.

Example:
    from hpp_exec import execute_segments
    from hpp_exec.gripper import segments_from_graph

    # Define your own gripper (any object with open() -> bool, close() -> bool)
    gripper = MyGripperController(...)

    configs, times, segments = segments_from_graph(
        path, graph,
        on_grasp=gripper.close,
        on_release=gripper.open,
    )

    execute_segments(
        segments, configs, times, joint_names=[...],
        time_parameterization="trapezoidal",
    )
"""

from __future__ import annotations

import inspect
from collections.abc import Mapping
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Callable, Iterable, List, Optional, Tuple

import numpy as np

if TYPE_CHECKING:
    from hpp_exec.segments import Segment

ActionSpec = (
    Callable[[], bool]
    | Callable[["GraspTransition"], bool]
    | Mapping[str, Callable[[], bool]]
)


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------


@dataclass
class GraspTransition:
    """A point in the trajectory where the manipulation graph transition changes."""

    config_index: int
    """Index in sampled configs where this transition occurs, or -1 if unsampled."""

    time: float
    """Time at this config."""

    grasps_before: set[str]
    """Active grasp names before the transition."""

    grasps_after: set[str]
    """Active grasp names after the transition."""

    state_before: str = ""
    """Constraint graph state before crossing the transition."""

    state_after: str = ""
    """Constraint graph state after crossing the transition."""

    transition_name: Optional[str] = None
    """Name of the graph transition crossed between state_before and state_after."""

    acquired: set[str] = field(default_factory=set)
    """New grasps (close gripper)."""

    released: set[str] = field(default_factory=set)
    """Lost grasps (open gripper)."""

    def __post_init__(self):
        if not self.acquired and not self.released:
            self.acquired = self.grasps_after - self.grasps_before
            self.released = self.grasps_before - self.grasps_after


@dataclass
class _PathTransitionInterval:
    start_param: float
    end_param: float
    state_before: str
    state_after: str
    transition_name: Optional[str]

    @property
    def identity(self) -> tuple[Optional[str], str, str]:
        return (self.transition_name, self.state_before, self.state_after)


# ---------------------------------------------------------------------------
# Constraint graph state parsing
# ---------------------------------------------------------------------------


def _parse_grasps_from_state_name(state_name: str) -> set[str]:
    """Extract active grasp descriptions from an HPP constraint graph state name.

    HPP state names encode active grasps, e.g.:
        "free"                                    -> set()
        "r_gripper grasps box/handle"             -> {"r_gripper grasps box/handle"}
        "r_gripper grasps box/handle : l_gripper grasps cup/handle"
            -> {"r_gripper grasps box/handle", "l_gripper grasps cup/handle"}

    The separator between multiple grasps is " : " (space-colon-space).
    """
    if not state_name or state_name.strip().lower() == "free":
        return set()

    # HPP uses " : " to separate multiple active grasps in state names
    parts = [p.strip() for p in state_name.split(" : ")]
    return {p for p in parts if " grasps " in f" {p.lower()} "}


def _grasp_label_from_transition_side(side: str) -> str:
    """Normalize one side of a transition name into a grasp label."""
    return side.strip().replace("  ", " ")


def _parse_grasp_event_from_transition_name(
    transition_name: Optional[str],
) -> tuple[set[str], set[str]]:
    """Extract acquired/released grasp labels from an HPP transition name.

    HPP manipulation transitions generated by the graph factory are typically
    named like:
        "fr3/gripper > box/handle | f_01"  (grasp)
        "fr3/gripper < box/handle | 0-0_12" (release)

    The state name may describe the resulting set of grasps, which is not
    enough to identify the event when states encode combinations such as
    "g1+g2". The transition name identifies the operation that was crossed.
    """
    if not transition_name:
        return set(), set()

    event_name = transition_name.split("|", 1)[0].strip()
    if " > " in event_name:
        gripper, handle = event_name.split(" > ", 1)
        return {
            f"{_grasp_label_from_transition_side(gripper)} grasps "
            f"{_grasp_label_from_transition_side(handle)}"
        }, set()

    if " < " in event_name:
        gripper, handle = event_name.split(" < ", 1)
        return set(), {
            f"{_grasp_label_from_transition_side(gripper)} grasps "
            f"{_grasp_label_from_transition_side(handle)}"
        }

    return set(), set()


def _callable_accepts_transition(action: Callable) -> bool:
    """Return whether action can be called with a GraspTransition argument."""
    try:
        signature = inspect.signature(action)
    except (TypeError, ValueError):
        return False

    positional = [
        p
        for p in signature.parameters.values()
        if p.kind
        in (
            inspect.Parameter.POSITIONAL_ONLY,
            inspect.Parameter.POSITIONAL_OR_KEYWORD,
        )
    ]
    has_varargs = any(
        p.kind == inspect.Parameter.VAR_POSITIONAL
        for p in signature.parameters.values()
    )
    required = [p for p in positional if p.default == inspect.Parameter.empty]
    return has_varargs or len(required) <= 1 <= len(positional)


def _action_keys_for_transition(
    transition: GraspTransition,
    event_grasps: set[str],
) -> list[str]:
    keys = []
    if transition.transition_name:
        keys.append(transition.transition_name)
    keys.extend(sorted(event_grasps))
    if transition.state_before or transition.state_after:
        keys.append(f"{transition.state_before} -> {transition.state_after}")
    return keys


def _resolve_action(
    action_spec: ActionSpec,
    transition: GraspTransition,
    event_grasps: set[str],
) -> Callable[[], bool]:
    """Resolve an action spec to the zero-arg callable stored on Segment."""
    if isinstance(action_spec, Mapping):
        for key in _action_keys_for_transition(transition, event_grasps):
            action = action_spec.get(key)
            if action is not None:
                if _callable_accepts_transition(action):
                    return lambda: action(transition)
                return action
        raise KeyError(
            "No action found for graph transition "
            f"{transition.transition_name!r}; tried keys "
            f"{_action_keys_for_transition(transition, event_grasps)!r}"
        )

    if _callable_accepts_transition(action_spec):
        return lambda: action_spec(transition)

    return action_spec


# ---------------------------------------------------------------------------
# Path-aware segment builder from constraint graph transitions
# ---------------------------------------------------------------------------


_PARAM_EPS = 1e-9


def _transition_name(transition) -> Optional[str]:
    name = getattr(transition, "name", None)
    if callable(name):
        return name()
    if name is not None:
        return str(name)
    return None


def _path_length(path) -> float:
    length = getattr(path, "length", None)
    if not callable(length):
        raise TypeError("path must provide length()")
    return float(length())


def _is_path_vector(path) -> bool:
    return callable(getattr(path, "numberPaths", None)) and callable(
        getattr(path, "pathAtRank", None)
    )


def _flatten_path_vector(path) -> list:
    subpaths = []
    for rank in range(int(path.numberPaths())):
        subpath = path.pathAtRank(rank)
        if _is_path_vector(subpath):
            subpaths.extend(_flatten_path_vector(subpath))
        else:
            subpaths.append(subpath)
    return subpaths


def _path_subintervals(path) -> list[tuple[float, float]]:
    if not _is_path_vector(path):
        raise TypeError("path must be an HPP PathVector")

    subpaths = _flatten_path_vector(path)
    if not subpaths:
        return []

    intervals = []
    cursor = 0.0
    for subpath in subpaths:
        length = _path_length(subpath)
        start = cursor
        end = start + length
        if end - start > _PARAM_EPS:
            intervals.append((start, end))
        cursor = end
    return intervals


def _extract_path_transition_intervals(path, graph) -> list[_PathTransitionInterval]:
    intervals: list[_PathTransitionInterval] = []
    for start, end in _path_subintervals(path):
        midpoint = start + 0.5 * (end - start)
        transition = graph.transitionAtParam(path, midpoint)
        state_before, state_after = graph.getNodesConnectedByTransition(transition)
        interval = _PathTransitionInterval(
            start_param=start,
            end_param=end,
            state_before=state_before,
            state_after=state_after,
            transition_name=_transition_name(transition),
        )

        if intervals and intervals[-1].identity == interval.identity:
            intervals[-1].end_param = interval.end_param
        else:
            intervals.append(interval)

    return intervals


def _uniform_sample_params(
    length: float, n_per_unit: int, min_samples: int
) -> list[float]:
    if length <= _PARAM_EPS:
        return [0.0]

    n_samples = max(int(length * n_per_unit), min_samples)
    n_samples = max(n_samples, 1)
    return [(i / n_samples) * length for i in range(n_samples + 1)]


def _dedupe_params(params: Iterable[float], length: float) -> list[float]:
    bounded = [min(max(float(p), 0.0), length) for p in params]
    ordered = sorted(bounded)

    deduped: list[float] = []
    for param in ordered:
        if deduped and abs(param - deduped[-1]) <= _PARAM_EPS:
            continue
        deduped.append(param)
    return deduped


def _sample_path_at(path, param: float) -> np.ndarray:
    result = path(param)
    if isinstance(result, tuple):
        config, success = result
        if not success:
            raise RuntimeError(f"path evaluation failed at parameter {param}")
    else:
        config = result
    return np.array(config)


def _find_param_index(times: list[float], param: float) -> int:
    for index, time in enumerate(times):
        if abs(time - param) <= _PARAM_EPS:
            return index
    raise ValueError(f"parameter {param} was not sampled")


def _looks_like_factory_transient_state(state_name: str) -> bool:
    return " > " in state_name or " < " in state_name


def _transition_from_interval(
    interval: _PathTransitionInterval,
    config_index: int,
) -> GraspTransition:
    grasps_before = _parse_grasps_from_state_name(interval.state_before)
    grasps_after = _parse_grasps_from_state_name(interval.state_after)
    if grasps_before or grasps_after:
        acquired = grasps_after - grasps_before
        released = grasps_before - grasps_after
    elif _looks_like_factory_transient_state(
        interval.state_before
    ) or _looks_like_factory_transient_state(interval.state_after):
        acquired, released = set(), set()
    else:
        acquired, released = _parse_grasp_event_from_transition_name(
            interval.transition_name
        )
    transition = GraspTransition(
        config_index=config_index,
        time=interval.start_param,
        state_before=interval.state_before,
        state_after=interval.state_after,
        transition_name=interval.transition_name,
        grasps_before=grasps_before,
        grasps_after=grasps_after,
        acquired=acquired,
        released=released,
    )
    return transition


def extract_path_grasp_transitions(path, graph) -> List[GraspTransition]:
    """Return grasp/release events encoded by an HPP manipulation path.

    The path is inspected through its continuous HPP ``PathVector`` structure:
    each subpath midpoint is mapped back to a constraint-graph transition with
    ``graph.transitionAtParam``. No sampled configurations are used to detect
    grasp boundaries.
    """
    transitions = []
    for interval in _extract_path_transition_intervals(path, graph):
        transition = _transition_from_interval(interval, config_index=-1)
        if transition.acquired or transition.released:
            transitions.append(transition)
    return transitions


def segments_from_graph(
    path,
    graph,
    on_grasp: ActionSpec,
    on_release: ActionSpec,
    *,
    n_per_unit: int = 50,
    min_samples: int = 50,
    sample_params: Optional[Iterable[float]] = None,
) -> Tuple[List[np.ndarray], List[float], List["Segment"]]:
    """Sample an HPP manipulation path and split it at grasp/release events.

    All graph-transition boundaries are included in the sampled waypoint list,
    but execution segments are only split where a gripper action is needed.

    Args:
        path: HPP manipulation path.
        graph: HPP manipulation graph.
        on_grasp: Action to run before intervals that acquire a grasp.
        on_release: Action to run before intervals that release a grasp.
        n_per_unit: Number of regular samples per path-parameter unit.
        min_samples: Minimum number of regular samples.
        sample_params: Optional path parameters to use instead of regular sampling.

    Returns:
        ``(configs, times, segments)``. ``times`` are geometric path parameters.
    """
    from hpp_exec.segments import Segment

    length = _path_length(path)
    intervals = _extract_path_transition_intervals(path, graph)

    if sample_params is None:
        params = _uniform_sample_params(length, n_per_unit, min_samples)
    else:
        params = list(sample_params)

    boundary_params = [0.0, length]
    for interval in intervals:
        boundary_params.extend((interval.start_param, interval.end_param))

    times = _dedupe_params([*params, *boundary_params], length)
    configs = [_sample_path_at(path, param) for param in times]

    if not intervals:
        return configs, times, [Segment(0, len(configs))]

    event_intervals = []
    for interval in intervals:
        transition = _transition_from_interval(interval, config_index=-1)
        if transition.acquired or transition.released:
            event_intervals.append(interval)

    if not event_intervals:
        return configs, times, [Segment(0, len(configs))]

    split_params = _dedupe_params(
        [0.0, *(interval.start_param for interval in event_intervals), length],
        length,
    )

    segments = []
    for i in range(len(split_params) - 1):
        start_param = split_params[i]
        end_param = split_params[i + 1]
        start_index = _find_param_index(times, start_param)
        end_index = _find_param_index(times, end_param)
        if end_index <= start_index:
            continue

        pre_actions = []
        for interval in event_intervals:
            if abs(interval.start_param - start_param) > _PARAM_EPS:
                continue

            transition = _transition_from_interval(interval, start_index)
            if transition.acquired:
                pre_actions.append(
                    _resolve_action(on_grasp, transition, transition.acquired)
                )
            if transition.released:
                pre_actions.append(
                    _resolve_action(on_release, transition, transition.released)
                )

        segments.append(Segment(start_index, end_index + 1, pre_actions=pre_actions))

    if not segments:
        segments.append(Segment(0, len(configs)))

    return configs, times, segments
